name: Pull request
description: Create a pull request
body:
  - type: markdown
    attributes:
      value: |
        Thanks for opening a pull request!
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
